server:
  port: 8083



resilience4j:
  circuitbreaker:
    configs:
      customCircuitBreakerConfig:
        registerHealthIndicator: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: COUNT_BASED
    instances:
      myCircuitBreaker: # this name is used in the annotation
        baseConfig: customCircuitBreakerConfig

spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:h2:~/inventory-service
    driver-class-name: org.h2.Driver
    username:
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"



springdoc:
  api-docs:
    groups:
      enabled: true
    path: /inventory-service/v3/api-docs
  swagger-ui:
    enabled: false